[workspace]
members = ["./syntastic-queries", "./syntastic-parsers"]

[package]
name = "syntastic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["serde", "parsers-all"]

parsers-some = ["syntastic-parsers/some", "syntastic-queries/some"]
parsers-most = ["parsers-some", "syntastic-parsers/most", "syntastic-queries/most"]
parsers-all = ["parsers-most", "syntastic-parsers/all", "syntastic-queries/all"]

[dependencies]
serde = { version = "1.0.160", features = ["derive"], optional = true }
thiserror = "1.0.40"
tree-sitter = "0.20.10"
tree-sitter-highlight = "0.20.1"

syntastic-parsers = { version = "0.1.0", path = "./syntastic-parsers", default-features = false, optional = true }
syntastic-queries = { version = "0.1.0", path = "./syntastic-queries", default-features = false, optional = true }
