[workspace]
members = [
    "./xtask",
    "./rsexpr",
    "./lua-pattern",
    "./syntastica-queries",
    "./syntastica-parsers-git",
    "./syntastica-macros",
    "./syntastica-themes",
]

package.authors = ["RubixDev"]
package.license = "GPL-3.0-only"
package.repository = "https://github.com/RubixDev/syntastica"

[package]
name = "syntastica"
version = "0.1.1"
authors.workspace = true
edition = "2021"
keywords = ["tree-sitter", "syntect", "highlight", "parsing", "syntax"]
license.workspace = true
repository.workspace = true
description = "Modern and easy syntax highlighting using tree-sitter"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["queries"]

queries = [
    "dep:syntastica-macros",
    "dep:syntastica-queries",
]

[dependencies]
serde = { version = "1.0.160", features = ["derive"], optional = true }
thiserror = "1.0.40"

tree-sitter = "0.20.10"
tree-sitter-highlight = "0.20.1"

syntastica-macros = { version = "0.1.0", path = "./syntastica-macros", optional = true }
syntastica-queries = { version = "0.1.0", path = "./syntastica-queries", optional = true }

[dev-dependencies]
syntastica-parsers-git = { version = "0.1.0", path = "./syntastica-parsers-git", features = ["all"] }
syntastica-themes = { version = "0.1.0", path = "./syntastica-themes" }
toml = "0.7.4"

[build-dependencies]
rustc_version = "0.4.0"

[package.metadata.docs.rs]
all-features = true
