[workspace]
members = ["./syntastica-queries", "./syntastica-parsers"]

[package]
name = "syntastica"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["serde", "parsers-all"]

parsers-some = ["syntastica-parsers/some", "syntastica-queries/some"]
parsers-most = ["parsers-some", "syntastica-parsers/most", "syntastica-queries/most"]
parsers-all = ["parsers-most", "syntastica-parsers/all", "syntastica-queries/all"]

[dependencies]
serde = { version = "1.0.160", features = ["derive"], optional = true }
thiserror = "1.0.40"
tree-sitter = "0.20.10"
tree-sitter-highlight = "0.20.1"

syntastica-parsers = { version = "0.1.0", path = "./syntastica-parsers", default-features = false, optional = true }
syntastica-queries = { version = "0.1.0", path = "./syntastica-queries", default-features = false, optional = true }
