[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
once_cell = "1.17.1"
regex = "1.8.1"
syntastica = { version = "0.1.1", path = ".." }
syntastica-macros = { version = "0.1.0", path = "../syntastica-macros" }
syntastica-parsers-git = { version = "0.1.0", path = "../syntastica-parsers-git", features = ["all"] }
tree-sitter = "0.20.10"
