[build]
target = "wasm32-unknown-emscripten"

[target.wasm32-unknown-emscripten]
rustflags = [
    "-Clink-arg=-sEXPORTED_FUNCTIONS=_highlight,_init,_free,_malloc",
    "-Clink-arg=-sEXPORT_ES6=1",
    "-Clink-arg=-sMODULARIZE=1",
    "-Clink-arg=-sEXPORTED_RUNTIME_METHODS=stringToNewUTF8,UTF8ToString,getValue,setValue",
]
