[package]
name = "syntastica-macros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
once_cell = "1.17.1"
proc-macro2 = "1.0.58"
quote = "1.0.27"
serde = { version = "1.0.163", features = ["derive"] }
toml = "0.7.4"
