[package]
name = "syntastica-queries"
version = "0.2.0"
authors.workspace = true
edition = "2021"
license.workspace = true
repository.workspace = true
description = "Collection of tree-sitter queries for syntastica"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
once_cell = "1.17.1"
syntastica = { version = "0.2.0", path = ".." }
syntastica-macros = { version = "0.2.0", path = "../syntastica-macros" }
syntastica-parsers-git = { version = "0.1.1", path = "../syntastica-parsers-git", features = ["all"] }
tree-sitter = "0.20.10"

[build-dependencies]
rustc_version = "0.4.0"

[package.metadata.docs.rs]
all-features = true
