[package]
name = "syntastica-queries"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[features]
default = []

some = [
    "dep:syntastica-parsers",
    "syntastica-parsers?/some",
]
most = [
    "some",
    "syntastica-parsers?/most",
]
all = [
    "most",
    "syntastica-parsers?/all",
]

[dependencies]
quote = "1.0.26"
tree-sitter = "0.20.10"

once_cell = "1.17.1"
regex = "1.7.3"
syntastica-macros = { version = "0.1.0", path = "../syntastica-macros" }
syntastica-parsers = { version = "0.1.0", path = "../syntastica-parsers", optional = true }

[dev-dependencies]
syntastica-parsers = { version = "0.1.0", path = "../syntastica-parsers" }
